version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    network_mode: host
    restart: always

  gofaxserver:
    image: gofaxserver:latest
    container_name: gofaxserver
    env_file:
      - .env
    volumes:
      - /etc/gofaxserver/config.json:/etc/gofaxserver/config.json
      - ./tmp:/tmp
    network_mode: host
    restart: always