version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - fax-network

  gofaxserver:
    image: gofaxserver:latest
    container_name: gofaxserver
    env_file:
      - .env
    restart: always
    networks:
      - fax-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config.json:/etc/gofaxserver/config.json
    ports:
      - "80:80"
      - "8022:8022"

networks:
  fax-network:
    driver: bridge